In [5]:
import numpy as np
import pandas as pd
import sketch
import pandas_profiling
from pandas_profiling import ProfileReport

C:\Users\Aravind\AppData\Local\Temp\ipykernel_25584\2510045108.py:4: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  import pandas_profiling


In [6]:
import sweetviz as sv

In [7]:
import seaborn as sb

## Data Importing

In [8]:
data = pd.read_csv("youtube_dislike_dataset.csv")
data

video_id                                              title  \
0      --0bCF-iK2E               Jadon Sancho  Magical Skills & Goals   
1      --14w5SOEUs                 Migos - Avalanche (Official Video)   
2      --40TEbZ9Is         Supporting Actress in a Comedy: 73rd Emmys   
3      --4tfbSyYDE            JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO   
4      --DKkzWVh-E                       Why Retaining Walls Collapse   
...            ...                                                ...   
37417  zzd4ydafGR0  Lil Tjay - Calling My Phone (feat. 6LACK) [Off...   
37418  zziBybeSAtw  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   
37419  zzk09ESX7e0                 [MV]  (MAMAMOO) - Where Are We Now   
37420  zzmQEb0Em5I              FELLIPE ESCUDERO- Master Podcast  #12   
37421  zzxPZwaA-8w  Gareth Bale brace secures dramatic comeback on...   

                     channel_id          channel_title         published_at  \
0      UC6UL29enLNe4mqwTfAyeNuw             Bundesliga  2021-07-01 10:00:00   
1      UCGIelM2Dj3zza3xyV3pL3WQ              MigosVEVO  2021-06-10 16:00:00   
2      UClBKH8yZRcM4AsRjDVEdjMg     Television Academy  2021-09-20 01:03:32   
3      UCsmXiDP8S40uBeJYxvyulmA                    JO1  2021-03-03 10:00:17   
4      UCMOqf8ab-42UUQIdVoKwjlQ  Practical Engineering  2021-12-07 13:00:00   
...                         ...                    ...                  ...   
37417  UCEB4a5o_6KfjxHwNMnmj54Q               Lil Tjay  2021-02-12 05:03:49   
37418  UCWJ2lWNubArHWmf3FIHbfcQ                    NBA  2021-01-16 05:39:05   
37419  UCuhAUMLzJxlP1W7mEk0_6lA                MAMAMOO  2021-06-02 09:00:10   
37420  UC8NjnNWMsRqq11NYvHAQb1g         Master Podcast  2020-10-20 20:59:30   
37421  UCEg25rdRZXg32iwai6N6l0w      Tottenham Hotspur  2021-05-23 21:00:31   

       view_count    likes  dislikes  comment_count  \
0         1048888    19515       226           1319   
1        15352638   359277      7479          18729   
2          925281    11212       401            831   
3         2641597    39131       441           3745   
4          715724    32887       367           1067   
...           ...      ...       ...            ...   
37417   120408275  2180780     35871          81360   
37418     2841917    20759      1049           2624   
37419    13346678   720854      4426          90616   
37420      252057    19198      1234           1471   
37421     2252090    34063       868           2004   

                                                    tags  \
0      football soccer ftbol alemn Bundesliga season ...   
1      Migos Avalanche Quality Control Music/Motown R...   
2                                                          
3      PRODUCE101JAPAN              JO1   TheSTAR STA...   
4      retaining wall New Jersey highway Direct Conne...   
...                                                  ...   
37417  Lil Tjay Steady Calling My Phone Calling My Ph...   
37418  NBA G League Basketball game-0022000187 Lakers...   
37419  MAMAMOO  WAW  WAW MAMAMOO WAW Where Are We Now...   
37420  master masterpodcast lord lord vinheteiro z z ...   
37421  Spurs Tottenham Hotspur   Tottenham Leicester ...   

                                             description  \
0      Enjoy the best skills and goals from Jadon San...   
1      Watch the the official video for Migos - "Aval...   
2      Hannah Waddingham wins the Emmy for Supporting...   
3      JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO\n\n---...   
4      One of the most important (and innocuous) part...   
...                                                  ...   
37417  Official video for "Calling My Phone" by Lil T...   
37418  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   
37419  [MV]  (MAMAMOO) - Where Are We Now\n\nInstagra...   
37420  DOCTOR HAIR\nhttps://www.thedoctorhair.com/?fb...   
37421  Two minute highlights from Tottenham Hotspur's...   

                                                comments  
0      Respect to Dort

## 1: Top 5 and Bottom 5 records


In [9]:
top_5_records = data.head()
top_5_records

video_id                                       title  \
0  --0bCF-iK2E        Jadon Sancho  Magical Skills & Goals   
1  --14w5SOEUs          Migos - Avalanche (Official Video)   
2  --40TEbZ9Is  Supporting Actress in a Comedy: 73rd Emmys   
3  --4tfbSyYDE     JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO   
4  --DKkzWVh-E                Why Retaining Walls Collapse   

                 channel_id          channel_title         published_at  \
0  UC6UL29enLNe4mqwTfAyeNuw             Bundesliga  2021-07-01 10:00:00   
1  UCGIelM2Dj3zza3xyV3pL3WQ              MigosVEVO  2021-06-10 16:00:00   
2  UClBKH8yZRcM4AsRjDVEdjMg     Television Academy  2021-09-20 01:03:32   
3  UCsmXiDP8S40uBeJYxvyulmA                    JO1  2021-03-03 10:00:17   
4  UCMOqf8ab-42UUQIdVoKwjlQ  Practical Engineering  2021-12-07 13:00:00   

   view_count   likes  dislikes  comment_count  \
0     1048888   19515       226           1319   
1    15352638  359277      7479          18729   
2      925281   11212       401            831   
3     2641597   39131       441           3745   
4      715724   32887       367           1067   

                                                tags  \
0  football soccer ftbol alemn Bundesliga season ...   
1  Migos Avalanche Quality Control Music/Motown R...   
2                                                      
3  PRODUCE101JAPAN              JO1   TheSTAR STA...   
4  retaining wall New Jersey highway Direct Conne...   

                                         description  \
0  Enjoy the best skills and goals from Jadon San...   
1  Watch the the official video for Migos - "Aval...   
2  Hannah Waddingham wins the Emmy for Supporting...   
3  JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO\n\n---...   
4  One of the most important (and innocuous) part...   

                                            comments  
0  Respect to Dortmund fans,must be sad losing hi...  
1  Migos just makes me want to live my live to th...  
2  Hannah's energy bursts through any screen. Wel...  
3  youngVer><  REN is really PERFECT. It's not ju...  
4   Keep up with all my projects here: https://pr...

In [10]:
bottom_5_records = data.tail()
bottom_5_records

video_id                                              title  \
37417  zzd4ydafGR0  Lil Tjay - Calling My Phone (feat. 6LACK) [Off...   
37418  zziBybeSAtw  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   
37419  zzk09ESX7e0                 [MV]  (MAMAMOO) - Where Are We Now   
37420  zzmQEb0Em5I              FELLIPE ESCUDERO- Master Podcast  #12   
37421  zzxPZwaA-8w  Gareth Bale brace secures dramatic comeback on...   

                     channel_id      channel_title         published_at  \
37417  UCEB4a5o_6KfjxHwNMnmj54Q           Lil Tjay  2021-02-12 05:03:49   
37418  UCWJ2lWNubArHWmf3FIHbfcQ                NBA  2021-01-16 05:39:05   
37419  UCuhAUMLzJxlP1W7mEk0_6lA            MAMAMOO  2021-06-02 09:00:10   
37420  UC8NjnNWMsRqq11NYvHAQb1g     Master Podcast  2020-10-20 20:59:30   
37421  UCEg25rdRZXg32iwai6N6l0w  Tottenham Hotspur  2021-05-23 21:00:31   

       view_count    likes  dislikes  comment_count  \
37417   120408275  2180780     35871          81360   
37418     2841917    20759      1049           2624   
37419    13346678   720854      4426          90616   
37420      252057    19198      1234           1471   
37421     2252090    34063       868           2004   

                                                    tags  \
37417  Lil Tjay Steady Calling My Phone Calling My Ph...   
37418  NBA G League Basketball game-0022000187 Lakers...   
37419  MAMAMOO  WAW  WAW MAMAMOO WAW Where Are We Now...   
37420  master masterpodcast lord lord vinheteiro z z ...   
37421  Spurs Tottenham Hotspur   Tottenham Leicester ...   

                                             description  \
37417  Official video for "Calling My Phone" by Lil T...   
37418  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   
37419  [MV]  (MAMAMOO) - Where Are We Now\n\nInstagra...   
37420  DOCTOR HAIR\nhttps://www.thedoctorhair.com/?fb...   
37421  Two minute highlights from Tottenham Hotspur's...   

                                                comments  
37417  'DESTINED 2 WIN' OUT NOW !! https://liltjay.ln...  
37418  Montrezl Harrell is going crazy with the rebou...  
37419  I honestly do not know why this song hit so ha...  
37420  Foi um prazer passar esta tarde com vocs debat...  
37421  Thank you Kane for everything you have given t...

## 2: Info and Shape of Data

In [11]:
info = data.info()
info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37422 entries, 0 to 37421
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   video_id       37422 non-null  object
 1   title          37422 non-null  object
 2   channel_id     37422 non-null  object
 3   channel_title  37422 non-null  object
 4   published_at   37422 non-null  object
 5   view_count     37422 non-null  int64 
 6   likes          37422 non-null  int64 
 7   dislikes       37422 non-null  int64 
 8   comment_count  37422 non-null  int64 
 9   tags           37422 non-null  object
 10  description    37422 non-null  object
 11  comments       37264 non-null  object
dtypes: int64(4), object(8)
memory usage: 3.4+ MB


In [12]:
shape = data.shape
shape

(37422, 12)

Inference: From the above, we can tell that there are 4 integer type data columns i.e. there are 4 numerical type data columns. Also, there are 8 object type data columns i.e. 8 categorical columns. The shape of the dataset is (32422 , 12). It indicates that there are 37422 rows and 12 columns

## 3: Percentange of null values

In [13]:
sum_null_values = data.isnull().sum()
sum_null_values

video_id           0
title              0
channel_id         0
channel_title      0
published_at       0
view_count         0
likes              0
dislikes           0
comment_count      0
tags               0
description        0
comments         158
dtype: int64

In [14]:
total_rows = 37422
null_values = 158

In [15]:
percentage_null_values = ((null_values)/total_rows)*100       
percentage_null_values                                                    #percentage = (values/total)*100

0.4222115333226444

The above analysis shows that null values constitute to 0.42% of the total data. Thee null values in the data cannot be imputed with other values as the null values are found in 'comments' whose data type is object. Also, comments differ from person to person, video to video and value/string cannot be fit in all the nulls with respect to all the other data given thus, dropping the comments column.

In [16]:
data.drop(columns = "comments")

video_id                                              title  \
0      --0bCF-iK2E               Jadon Sancho  Magical Skills & Goals   
1      --14w5SOEUs                 Migos - Avalanche (Official Video)   
2      --40TEbZ9Is         Supporting Actress in a Comedy: 73rd Emmys   
3      --4tfbSyYDE            JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO   
4      --DKkzWVh-E                       Why Retaining Walls Collapse   
...            ...                                                ...   
37417  zzd4ydafGR0  Lil Tjay - Calling My Phone (feat. 6LACK) [Off...   
37418  zziBybeSAtw  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   
37419  zzk09ESX7e0                 [MV]  (MAMAMOO) - Where Are We Now   
37420  zzmQEb0Em5I              FELLIPE ESCUDERO- Master Podcast  #12   
37421  zzxPZwaA-8w  Gareth Bale brace secures dramatic comeback on...   

                     channel_id          channel_title         published_at  \
0      UC6UL29enLNe4mqwTfAyeNuw             Bundesliga  2021-07-01 10:00:00   
1      UCGIelM2Dj3zza3xyV3pL3WQ              MigosVEVO  2021-06-10 16:00:00   
2      UClBKH8yZRcM4AsRjDVEdjMg     Television Academy  2021-09-20 01:03:32   
3      UCsmXiDP8S40uBeJYxvyulmA                    JO1  2021-03-03 10:00:17   
4      UCMOqf8ab-42UUQIdVoKwjlQ  Practical Engineering  2021-12-07 13:00:00   
...                         ...                    ...                  ...   
37417  UCEB4a5o_6KfjxHwNMnmj54Q               Lil Tjay  2021-02-12 05:03:49   
37418  UCWJ2lWNubArHWmf3FIHbfcQ                    NBA  2021-01-16 05:39:05   
37419  UCuhAUMLzJxlP1W7mEk0_6lA                MAMAMOO  2021-06-02 09:00:10   
37420  UC8NjnNWMsRqq11NYvHAQb1g         Master Podcast  2020-10-20 20:59:30   
37421  UCEg25rdRZXg32iwai6N6l0w      Tottenham Hotspur  2021-05-23 21:00:31   

       view_count    likes  dislikes  comment_count  \
0         1048888    19515       226           1319   
1        15352638   359277      7479          18729   
2          925281    11212       401            831   
3         2641597    39131       441           3745   
4          715724    32887       367           1067   
...           ...      ...       ...            ...   
37417   120408275  2180780     35871          81360   
37418     2841917    20759      1049           2624   
37419    13346678   720854      4426          90616   
37420      252057    19198      1234           1471   
37421     2252090    34063       868           2004   

                                                    tags  \
0      football soccer ftbol alemn Bundesliga season ...   
1      Migos Avalanche Quality Control Music/Motown R...   
2                                                          
3      PRODUCE101JAPAN              JO1   TheSTAR STA...   
4      retaining wall New Jersey highway Direct Conne...   
...                                                  ...   
37417  Lil Tjay Steady Calling My Phone Calling My Ph...   
37418  NBA G League Basketball game-0022000187 Lakers...   
37419  MAMAMOO  WAW  WAW MAMAMOO WAW Where Are We Now...   
37420  master masterpodcast lord lord vinheteiro z z ...   
37421  Spurs Tottenham Hotspur   Tottenham Leicester ...   

                                             description  
0      Enjoy the best skills and goals from Jadon San...  
1      Watch the the official video for Migos - "Aval...  
2      Hannah Waddingham wins the Emmy for Supporting...  
3      JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO\n\n---...  
4      One of the most important (and innocuous) part...  
...                                                  ...  
37417  Official video for "Calling My Phone" by Lil T...  
37418  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...  
37419  [MV]  (MAMAMOO) - Where Are We Now\n\nInstagra...  
37420  DOCTOR HAIR\nhttps://www.thedoctorhair.com/?fb...  
37421  Two minute highlights from Tottenham Hotspur's...  

[37422 rows x 11 columns]

As seen above, we have removed the column 'comments'

## 4: Statistical summary

In [17]:
summary = data.describe()
summary

view_count         likes      dislikes  comment_count
count  3.742200e+04  3.742200e+04  3.742200e+04   3.742200e+04
mean   5.697838e+06  1.668147e+05  4.989862e+03   9.924930e+03
std    2.426622e+07  5.375670e+05  3.070824e+04   1.171003e+05
min    2.036800e+04  0.000000e+00  0.000000e+00   0.000000e+00
25%    5.122970e+05  1.323350e+04  2.810000e+02   9.000000e+02
50%    1.319078e+06  4.233050e+04  7.960000e+02   2.328000e+03
75%    3.670231e+06  1.304698e+05  2.461750e+03   6.184000e+03
max    1.322797e+09  3.183768e+07  2.397733e+06   1.607103e+07

In [18]:
ProfileReport(data)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

## 5: Convert object datatype to datetime datatype 

In [19]:
data['published_at'] = pd.to_datetime(data['published_at'])

In [20]:
data

video_id                                              title  \
0      --0bCF-iK2E               Jadon Sancho  Magical Skills & Goals   
1      --14w5SOEUs                 Migos - Avalanche (Official Video)   
2      --40TEbZ9Is         Supporting Actress in a Comedy: 73rd Emmys   
3      --4tfbSyYDE            JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO   
4      --DKkzWVh-E                       Why Retaining Walls Collapse   
...            ...                                                ...   
37417  zzd4ydafGR0  Lil Tjay - Calling My Phone (feat. 6LACK) [Off...   
37418  zziBybeSAtw  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   
37419  zzk09ESX7e0                 [MV]  (MAMAMOO) - Where Are We Now   
37420  zzmQEb0Em5I              FELLIPE ESCUDERO- Master Podcast  #12   
37421  zzxPZwaA-8w  Gareth Bale brace secures dramatic comeback on...   

                     channel_id          channel_title        published_at  \
0      UC6UL29enLNe4mqwTfAyeNuw             Bundesliga 2021-07-01 10:00:00   
1      UCGIelM2Dj3zza3xyV3pL3WQ              MigosVEVO 2021-06-10 16:00:00   
2      UClBKH8yZRcM4AsRjDVEdjMg     Television Academy 2021-09-20 01:03:32   
3      UCsmXiDP8S40uBeJYxvyulmA                    JO1 2021-03-03 10:00:17   
4      UCMOqf8ab-42UUQIdVoKwjlQ  Practical Engineering 2021-12-07 13:00:00   
...                         ...                    ...                 ...   
37417  UCEB4a5o_6KfjxHwNMnmj54Q               Lil Tjay 2021-02-12 05:03:49   
37418  UCWJ2lWNubArHWmf3FIHbfcQ                    NBA 2021-01-16 05:39:05   
37419  UCuhAUMLzJxlP1W7mEk0_6lA                MAMAMOO 2021-06-02 09:00:10   
37420  UC8NjnNWMsRqq11NYvHAQb1g         Master Podcast 2020-10-20 20:59:30   
37421  UCEg25rdRZXg32iwai6N6l0w      Tottenham Hotspur 2021-05-23 21:00:31   

       view_count    likes  dislikes  comment_count  \
0         1048888    19515       226           1319   
1        15352638   359277      7479          18729   
2          925281    11212       401            831   
3         2641597    39131       441           3745   
4          715724    32887       367           1067   
...           ...      ...       ...            ...   
37417   120408275  2180780     35871          81360   
37418     2841917    20759      1049           2624   
37419    13346678   720854      4426          90616   
37420      252057    19198      1234           1471   
37421     2252090    34063       868           2004   

                                                    tags  \
0      football soccer ftbol alemn Bundesliga season ...   
1      Migos Avalanche Quality Control Music/Motown R...   
2                                                          
3      PRODUCE101JAPAN              JO1   TheSTAR STA...   
4      retaining wall New Jersey highway Direct Conne...   
...                                                  ...   
37417  Lil Tjay Steady Calling My Phone Calling My Ph...   
37418  NBA G League Basketball game-0022000187 Lakers...   
37419  MAMAMOO  WAW  WAW MAMAMOO WAW Where Are We Now...   
37420  master masterpodcast lord lord vinheteiro z z ...   
37421  Spurs Tottenham Hotspur   Tottenham Leicester ...   

                                             description  \
0      Enjoy the best skills and goals from Jadon San...   
1      Watch the the official video for Migos - "Aval...   
2      Hannah Waddingham wins the Emmy for Supporting...   
3      JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO\n\n---...   
4      One of the most important (and innocuous) part...   
...                                                  ...   
37417  Official video for "Calling My Phone" by Lil T...   
37418  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   
37419  [MV]  (MAMAMOO) - Where Are We Now\n\nInstagra...   
37420  DOCTOR HAIR\nhttps://www.thedoctorhair.com/?fb...   
37421  Two minute highlights from Tottenham Hotspur's...   

                                                comments  
0      Respect to Dortmund fans,mu

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37422 entries, 0 to 37421
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   video_id       37422 non-null  object        
 1   title          37422 non-null  object        
 2   channel_id     37422 non-null  object        
 3   channel_title  37422 non-null  object        
 4   published_at   37422 non-null  datetime64[ns]
 5   view_count     37422 non-null  int64         
 6   likes          37422 non-null  int64         
 7   dislikes       37422 non-null  int64         
 8   comment_count  37422 non-null  int64         
 9   tags           37422 non-null  object        
 10  description    37422 non-null  object        
 11  comments       37264 non-null  object        
dtypes: datetime64[ns](1), int64(4), object(7)
memory usage: 3.4+ MB


By using the pd.to_datetime function of pandas, the published_at column is converted to datetime format.

## 6: Creating a new published_month column

In [22]:
data['published_month'] = data['published_at'].dt.month 

In [23]:
data

video_id                                              title  \
0      --0bCF-iK2E               Jadon Sancho  Magical Skills & Goals   
1      --14w5SOEUs                 Migos - Avalanche (Official Video)   
2      --40TEbZ9Is         Supporting Actress in a Comedy: 73rd Emmys   
3      --4tfbSyYDE            JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO   
4      --DKkzWVh-E                       Why Retaining Walls Collapse   
...            ...                                                ...   
37417  zzd4ydafGR0  Lil Tjay - Calling My Phone (feat. 6LACK) [Off...   
37418  zziBybeSAtw  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   
37419  zzk09ESX7e0                 [MV]  (MAMAMOO) - Where Are We Now   
37420  zzmQEb0Em5I              FELLIPE ESCUDERO- Master Podcast  #12   
37421  zzxPZwaA-8w  Gareth Bale brace secures dramatic comeback on...   

                     channel_id          channel_title        published_at  \
0      UC6UL29enLNe4mqwTfAyeNuw             Bundesliga 2021-07-01 10:00:00   
1      UCGIelM2Dj3zza3xyV3pL3WQ              MigosVEVO 2021-06-10 16:00:00   
2      UClBKH8yZRcM4AsRjDVEdjMg     Television Academy 2021-09-20 01:03:32   
3      UCsmXiDP8S40uBeJYxvyulmA                    JO1 2021-03-03 10:00:17   
4      UCMOqf8ab-42UUQIdVoKwjlQ  Practical Engineering 2021-12-07 13:00:00   
...                         ...                    ...                 ...   
37417  UCEB4a5o_6KfjxHwNMnmj54Q               Lil Tjay 2021-02-12 05:03:49   
37418  UCWJ2lWNubArHWmf3FIHbfcQ                    NBA 2021-01-16 05:39:05   
37419  UCuhAUMLzJxlP1W7mEk0_6lA                MAMAMOO 2021-06-02 09:00:10   
37420  UC8NjnNWMsRqq11NYvHAQb1g         Master Podcast 2020-10-20 20:59:30   
37421  UCEg25rdRZXg32iwai6N6l0w      Tottenham Hotspur 2021-05-23 21:00:31   

       view_count    likes  dislikes  comment_count  \
0         1048888    19515       226           1319   
1        15352638   359277      7479          18729   
2          925281    11212       401            831   
3         2641597    39131       441           3745   
4          715724    32887       367           1067   
...           ...      ...       ...            ...   
37417   120408275  2180780     35871          81360   
37418     2841917    20759      1049           2624   
37419    13346678   720854      4426          90616   
37420      252057    19198      1234           1471   
37421     2252090    34063       868           2004   

                                                    tags  \
0      football soccer ftbol alemn Bundesliga season ...   
1      Migos Avalanche Quality Control Music/Motown R...   
2                                                          
3      PRODUCE101JAPAN              JO1   TheSTAR STA...   
4      retaining wall New Jersey highway Direct Conne...   
...                                                  ...   
37417  Lil Tjay Steady Calling My Phone Calling My Ph...   
37418  NBA G League Basketball game-0022000187 Lakers...   
37419  MAMAMOO  WAW  WAW MAMAMOO WAW Where Are We Now...   
37420  master masterpodcast lord lord vinheteiro z z ...   
37421  Spurs Tottenham Hotspur   Tottenham Leicester ...   

                                             description  \
0      Enjoy the best skills and goals from Jadon San...   
1      Watch the the official video for Migos - "Aval...   
2      Hannah Waddingham wins the Emmy for Supporting...   
3      JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO\n\n---...   
4      One of the most important (and innocuous) part...   
...                                                  ...   
37417  Official video for "Calling My Phone" by Lil T...   
37418  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   
37419  [MV]  (MAMAMOO) - Where Are We Now\n\nInstagra...   
37420  DOCTOR HAIR\nhttps://www.thedoctorhair.com/?fb...   
37421  Two minute highlights from Tottenham Hotspur's...   

                                                comments  published_month  
0      Respect to

## 7: Replacing months (1,2,3...) to (Jan,Feb,March....)

In [24]:
data['published_month'] = data['published_month'].replace({1:"Jan",2:"Feb",3:"March",4:"April",5:"May",6:"June",7:"July",8:"Aug",9:"Sept",10:"Oct",11:"Nov",12:"Dec"})

In [25]:
data

video_id                                              title  \
0      --0bCF-iK2E               Jadon Sancho  Magical Skills & Goals   
1      --14w5SOEUs                 Migos - Avalanche (Official Video)   
2      --40TEbZ9Is         Supporting Actress in a Comedy: 73rd Emmys   
3      --4tfbSyYDE            JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO   
4      --DKkzWVh-E                       Why Retaining Walls Collapse   
...            ...                                                ...   
37417  zzd4ydafGR0  Lil Tjay - Calling My Phone (feat. 6LACK) [Off...   
37418  zziBybeSAtw  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   
37419  zzk09ESX7e0                 [MV]  (MAMAMOO) - Where Are We Now   
37420  zzmQEb0Em5I              FELLIPE ESCUDERO- Master Podcast  #12   
37421  zzxPZwaA-8w  Gareth Bale brace secures dramatic comeback on...   

                     channel_id          channel_title        published_at  \
0      UC6UL29enLNe4mqwTfAyeNuw             Bundesliga 2021-07-01 10:00:00   
1      UCGIelM2Dj3zza3xyV3pL3WQ              MigosVEVO 2021-06-10 16:00:00   
2      UClBKH8yZRcM4AsRjDVEdjMg     Television Academy 2021-09-20 01:03:32   
3      UCsmXiDP8S40uBeJYxvyulmA                    JO1 2021-03-03 10:00:17   
4      UCMOqf8ab-42UUQIdVoKwjlQ  Practical Engineering 2021-12-07 13:00:00   
...                         ...                    ...                 ...   
37417  UCEB4a5o_6KfjxHwNMnmj54Q               Lil Tjay 2021-02-12 05:03:49   
37418  UCWJ2lWNubArHWmf3FIHbfcQ                    NBA 2021-01-16 05:39:05   
37419  UCuhAUMLzJxlP1W7mEk0_6lA                MAMAMOO 2021-06-02 09:00:10   
37420  UC8NjnNWMsRqq11NYvHAQb1g         Master Podcast 2020-10-20 20:59:30   
37421  UCEg25rdRZXg32iwai6N6l0w      Tottenham Hotspur 2021-05-23 21:00:31   

       view_count    likes  dislikes  comment_count  \
0         1048888    19515       226           1319   
1        15352638   359277      7479          18729   
2          925281    11212       401            831   
3         2641597    39131       441           3745   
4          715724    32887       367           1067   
...           ...      ...       ...            ...   
37417   120408275  2180780     35871          81360   
37418     2841917    20759      1049           2624   
37419    13346678   720854      4426          90616   
37420      252057    19198      1234           1471   
37421     2252090    34063       868           2004   

                                                    tags  \
0      football soccer ftbol alemn Bundesliga season ...   
1      Migos Avalanche Quality Control Music/Motown R...   
2                                                          
3      PRODUCE101JAPAN              JO1   TheSTAR STA...   
4      retaining wall New Jersey highway Direct Conne...   
...                                                  ...   
37417  Lil Tjay Steady Calling My Phone Calling My Ph...   
37418  NBA G League Basketball game-0022000187 Lakers...   
37419  MAMAMOO  WAW  WAW MAMAMOO WAW Where Are We Now...   
37420  master masterpodcast lord lord vinheteiro z z ...   
37421  Spurs Tottenham Hotspur   Tottenham Leicester ...   

                                             description  \
0      Enjoy the best skills and goals from Jadon San...   
1      Watch the the official video for Migos - "Aval...   
2      Hannah Waddingham wins the Emmy for Supporting...   
3      JO1'YOUNG (JO1 ver.)' PERFORMANCE VIDEO\n\n---...   
4      One of the most important (and innocuous) part...   
...                                                  ...   
37417  Official video for "Calling My Phone" by Lil T...   
37418  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   
37419  [MV]  (MAMAMOO) - Where Are We Now\n\nInstagra...   
37420  DOCTOR HAIR\nhttps://www.thedoctorhair.com/?fb...   
37421  Two minute highlights from Tottenham Hotspur's...   

                                                comments published_month  
0      Respect to 

## 8: Number of videos published each month in descending order

In [26]:
count = data['published_month'].value_counts()
count

Oct      4991
Sept     4880
Nov      4851
Aug      4262
Dec      3072
July     2340
June     2316
March    2258
Feb      2137
April    2126
Jan      2108
May      2081
Name: published_month, dtype: int64

In [27]:
count.sort_values(ascending = False)

Oct      4991
Sept     4880
Nov      4851
Aug      4262
Dec      3072
July     2340
June     2316
March    2258
Feb      2137
April    2126
Jan      2108
May      2081
Name: published_month, dtype: int64

In [28]:
unique_val_videoid = data["video_id"].unique()
unique_val_videoid

array(['--0bCF-iK2E', '--14w5SOEUs', '--40TEbZ9Is', ..., 'zzk09ESX7e0',
       'zzmQEb0Em5I', 'zzxPZwaA-8w'], dtype=object)

## 9: Finding unique counts of Video_id,Channel_id and Channel title

In [29]:
len(unique_val_videoid)

37422

In [30]:
unique_val_channelid = data["channel_id"].unique()
unique_val_channelid

array(['UC6UL29enLNe4mqwTfAyeNuw', 'UCGIelM2Dj3zza3xyV3pL3WQ',
       'UClBKH8yZRcM4AsRjDVEdjMg', ..., 'UC95x-m2toVa_BRmmQ6SrIYg',
       'UCb5jIJ27Ds32YE6xX3eIO3g', 'UC8NjnNWMsRqq11NYvHAQb1g'],
      dtype=object)

In [31]:
len(unique_val_channelid)

10961

In [32]:
unique_val_title = data["channel_title"].unique()

In [33]:
len(unique_val_title)

10883

## 10: Top and bottom 10 channel names with number of videos uploaded

In [34]:
count_channel = data["channel_title"].value_counts()

In [35]:
count_channel

Sky Sports Football    533
The United Stand       301
BT Sport               246
NBA                    209
NFL                    162
                      ... 
Blocktrainer             1
Movie Addicts            1
1 1 minute mom           1
FLORIN CERCEL            1
Master Podcast           1
Name: channel_title, Length: 10883, dtype: int64

In [36]:
count_channel.head(10)

Sky Sports Football    533
The United Stand       301
BT Sport               246
NBA                    209
NFL                    162
WWE                    122
SSSniperWolf            99
SSundee                 98
FORMULA 1               87
NHL                     86
Name: channel_title, dtype: int64

In [37]:
(count_channel.sort_values(ascending = False)).tail(10)

IAmEzinmaVEVO           1
VisitSeoul TV           1
StefflonDonVEVO         1
SGV Kannada Media       1
KHON2 News              1
HikacGames              1
Android                 1
  - SONGCHELIN GUIDE    1
SpideyLucas             1
Master Podcast          1
Name: channel_title, dtype: int64

## 11: Channels having maximum and minimum number of likes

In [38]:
max_likes = data.sort_values('likes',ascending = False)
max_likes.head(1)

video_id                          title                channel_id  \
26143  gdZLi9oWNZg  BTS () 'Dynamite' Official MV  UC3IZKseVpdzPSBaWxBxundA   

      channel_title        published_at  view_count     likes  dislikes  \
26143   HYBE LABELS 2020-08-21 03:58:10  1322796924  31837675   1814333   

       comment_count                   tags  \
26143       16071029  BIGHIT   BTS BANGTAN    

                                             description  \
26143  BTS () 'Dynamite' Official MV\n\n\nCredits:\nD...   

                                                comments published_month  
26143  Armys, we will strive for the mv to reach 100 ...             Aug

In [39]:
max_likes.tail(1)

video_id                                              title  \
18654  Uh-lqtF2yO8  Kim Kardashian's Must-See Moments on "Saturday...   

                     channel_id channel_title        published_at  view_count  \
18654  UCjDsbbzHgTrGc4Ff26TJtsA       E! News 2021-10-10 08:36:34      403616   

       likes  dislikes  comment_count  \
18654      0         0              0   

                                                    tags  \
18654  E! NEWS NOW WOCHIT CELEBRITIES TOP STORIES TOP...   

                                             description comments  \
18654  Kim Kardashian takes her @Saturday Night Live ...      NaN   

      published_month  
18654             Oct

Inference: The analysis shows that the maximum liked video is BTS() 'Dynamite' Official MV by HYBE Labels in the month of August. It has a like count of 31837675 and comment count of 16071029. The video with least number of likes is Kim Kardashian's Must-See Moments on "Saturday Night Live" published by E! News in the month of October. The number of likes is 0 and the number of comments is 0. It is clear that the View-counts of both the videos have a great difference.

## 12: Channels having maximum and minimum number of  dislikes

In [40]:
max_dislikes = data.sort_values('dislikes',ascending = False)
max_dislikes.head(1)

video_id                                title  \
13591  M0O7lLe4SmA  Cuties | Official Trailer | Netflix   

                     channel_id channel_title        published_at  view_count  \
13591  UCWOA1ZGywLbqmigxE4Qlvuw       Netflix 2020-08-18 14:00:00    17996395   

       likes  dislikes  comment_count  \
13591  94569   2397733         205009   

                                                    tags  \
13591  Cuties Mignonnes Netflix NetflixFilm Dance Mai...   

                                             description  \
13591  Eleven-year-old Amy starts to rebel against he...   

                                                comments published_month  
13591  I love how the mom is the bad guy for not lett...             Aug

In [41]:
max_dislikes.tail(1)

video_id                                              title  \
18654  Uh-lqtF2yO8  Kim Kardashian's Must-See Moments on "Saturday...   

                     channel_id channel_title        published_at  view_count  \
18654  UCjDsbbzHgTrGc4Ff26TJtsA       E! News 2021-10-10 08:36:34      403616   

       likes  dislikes  comment_count  \
18654      0         0              0   

                                                    tags  \
18654  E! NEWS NOW WOCHIT CELEBRITIES TOP STORIES TOP...   

                                             description comments  \
18654  Kim Kardashian takes her @Saturday Night Live ...      NaN   

      published_month  
18654             Oct

Inference: The analysis shows that the maximum disliked video is Cuties Official Trailer by Netflix in the month of August. It has a dislike count of 2397733 and comment count of 205009. The video with least number of dislikes is Kim Kardashian's Must-See Moments on "Saturday Night Live" published by E! News in the month of October. The number of dislikes is 0 and the number of comments is 0. It is clear that the View-counts of both the videos have a great difference.

## 13: Effect of number of views on dislikes

In [42]:
data.corr()

view_count     likes  dislikes  comment_count
view_count       1.000000  0.784229  0.684469       0.464392
likes            0.784229  1.000000  0.679817       0.580953
dislikes         0.684469  0.679817  1.000000       0.391739
comment_count    0.464392  0.580953  0.391739       1.000000

In [43]:
import matplotlib.pyplot as plt
plt.scatter(data['view_count'], data['dislikes'])
plt.xlabel('View Count')
plt.ylabel('dislikes')
plt.title('Views vs Dislikes')
plt.show()

C:\Users\Aravind\AppData\Local\Temp\ipykernel_25584\3600581712.py:6: UserWarning: Matplotlib is currently using module://matplotlib_inline.backend_inline, which is a non-GUI backend, so cannot show the figure.
  plt.show()


Innference: From the above analysis, it is clear that the number of dislikes has a significant relation with view_count. To support this claim, the above correlation table is a strong proof. With a correlation of 0.684469 which is almost equal to 0.7, there is a mid-strong correlation between dislikes and view_count. Also, apart from certain points, the graph also shows a positive correlation between the two.

## 14: Data of videos published in Jan Month

In [44]:
jan_data = data[data['published_month'] == 'Jan']
jan_data

video_id                                              title  \
27     -2Gwm7QfBnE                                    Q&A With Naisha   
48     -4sfXSHSxzA           SURPRISING BRENT WITH HIS TIKTOK CRUSH!!   
95     -AJD1Fc5rpQ  WE ARE HAVING A BABY! | finding out i'm pregna...   
103    -AuJiwjsmWk              Do Ugly Foods Taste Worse? Taste Test   
182    -JhqO2KWr5U                                   Schlatt gets fit   
...            ...                                                ...   
37300  zmzFL5bG-jc  DEVINE MON PERSONNAGE AVANT AKINATOR ! (c'est ...   
37329  zpzjex7qwrA  Lampard Sacked Within Days Rorys Misery | Chel...   
37345  zqyv-B6mnBM                 Lil Wayne - Ain't Got Time (Audio)   
37383  zwfu1-24T7Q  PRADA Cup Day 1 | Full Race Replay | PRADA Cup...   
37418  zziBybeSAtw  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   

                     channel_id       channel_title        published_at  \
27     UCYwNMbogQFzMccPSuy-pPWg           MianTwins 2021-01-21 00:05:47   
48     UCPpATKqmMV-CNRNWYaDUwiA        Alexa Rivera 2021-01-16 21:40:04   
95     UCVsTboAhpnuL6j-tDePvNwQ      Tess Christine 2021-01-03 21:53:48   
103    UCzpCc5n9hqiVC7HhPwcIKEg  Good Mythical MORE 2021-01-19 11:00:01   
182    UCWZp4y1jqBuvLtiyxSs_ZBw             Big guy 2021-01-24 22:50:57   
...                         ...                 ...                 ...   
37300  UCIlr3byh6wmXgcPx_Tm9Ocw             Piwerre 2021-01-16 16:12:19   
37329  UCkD-ZOixI0a9FjIExDsHsbg        The Kick Off 2021-01-03 20:13:49   
37345  UCO9zJy7HWrIS3ojB4Lr7Yqw           Lil Wayne 2021-01-21 05:00:10   
37383  UCo15ZYO_XDRU9LI30OPtxAg       America's Cup 2021-01-15 04:07:55   
37418  UCWJ2lWNubArHWmf3FIHbfcQ                 NBA 2021-01-16 05:39:05   

       view_count   likes  dislikes  comment_count  \
27         872372   38626       239            621   
48        6504784  262477      5779           7907   
95         533084   38965       119           1650   
103       1057077   22526       531            773   
182       1724965  119431       325           1578   
...           ...     ...       ...            ...   
37300      670357   54462       832           1249   
37329      428646   12060       296           1505   
37345     2238244   58925      2365           5539   
37383      317382    2008        83            192   
37418     2841917   20759      1049           2624   

                                                    tags  \
27                                                         
48                                                         
95                                                         
103    gmm good mythical morning rhettandlink rhett a...   
182    jschlatt big guy jschlatt highlights schlatt j...   
...                                                  ...   
37300  Piwerre frere de michou crouton among us devin...   
37329  Premier league Chelsea chelsea 1-3 Man City Ch...   
37345  lil wayne weezy weezy wednesday wayne carter y...   
37383  America's Cup Americas Cup AC36 AC75 Presented...   
37418  NBA G League Basketball game-0022000187 Lakers...   

                                             description  \
27     Hey Guys!!! this has been the most requested v...   
48     He had no idea! Thank you guys so much for wat...   
95     I am so happy to tell you that I am pregnant!!...   
103    Today, we're doing a blind taste test to deter...   
182                    #jschlatt #schlatt #bigguy #short   
...                                                  ...   
37300   Discord Piwerre : https://discord.gg/QBduPgAA...   
37329  The Kick Off watched Manchester City destroy C...   
37345  Official audio for Lil Wayne "Ain't Got Time",...   
37383  The opening day of the PRADA Cup in Auckland, ...   
37418  PELICANS at LAKERS | FULL GAME HIGHLIGHTS | Ja...   

                                                comments published_month  
27     I feel like Nate and Aishas personality match ...          

In [45]:
count_vids_in_jan = len(jan_data)
count_vids_in_jan

2108

Inference: The above analysis shows that there were 2108 videos uploaded in the month of January.

### The above data analysis has been an exploratory data analysis and the following inference has been made:

1. The total number of videos uploaded in the year is 37422.
2. Most number of videos was uploaded by Sky Sports Football.
3. There are 10883 unique channel titles.
4. In all of the variables, only comments have a missing values of 0.4%
5. The most number of videos was uploaded in October while the least number of videos were uploaded in the month of May.
6. There is a medium to strong correlation between 'likes and view_count' and 'dislikes and view_count'.